use std::str::FromStr;

#[derive(Debug, PartialEq, Eq, Hash)]
pub enum Position {
    SQ_00,
    SQ_1A,
    SQ_1B,
    SQ_1C,
    SQ_1D,
    SQ_1E,
    SQ_1F,
    SQ_1G,
    SQ_1H,
    SQ_1I,
    SQ_2A,
    SQ_2B,
    SQ_2C,
    SQ_2D,
    SQ_2E,
    SQ_2F,
    SQ_2G,
    SQ_2H,
    SQ_2I,
    SQ_3A,
    SQ_3B,
    SQ_3C,
    SQ_3D,
    SQ_3E,
    SQ_3F,
    SQ_3G,
    SQ_3H,
    SQ_3I,
    SQ_4A,
    SQ_4B,
    SQ_4C,
    SQ_4D,
    SQ_4E,
    SQ_4F,
    SQ_4G,
    SQ_4H,
    SQ_4I,
    SQ_5A,
    SQ_5B,
    SQ_5C,
    SQ_5D,
    SQ_5E,
    SQ_5F,
    SQ_5G,
    SQ_5H,
    SQ_5I,
    SQ_6A,
    SQ_6B,
    SQ_6C,
    SQ_6D,
    SQ_6E,
    SQ_6F,
    SQ_6G,
    SQ_6H,
    SQ_6I,
    SQ_7A,
    SQ_7B,
    SQ_7C,
    SQ_7D,
    SQ_7E,
    SQ_7F,
    SQ_7G,
    SQ_7H,
    SQ_7I,
    SQ_8A,
    SQ_8B,
    SQ_8C,
    SQ_8D,
    SQ_8E,
    SQ_8F,
    SQ_8G,
    SQ_8H,
    SQ_8I,
    SQ_9A,
    SQ_9B,
    SQ_9C,
    SQ_9D,
    SQ_9E,
    SQ_9F,
    SQ_9G,
    SQ_9H,
    SQ_9I,
}

impl FromStr for Position {
    type Err = ();

    fn from_str(input: &str) -> Result<Position, Self::Err> {
        match input {
            "00" => Ok(Position::SQ_00),

            "11" => Ok(Position::SQ_1A),
            "12" => Ok(Position::SQ_1B),
            "13" => Ok(Position::SQ_1C),
            "14" => Ok(Position::SQ_1D),
            "15" => Ok(Position::SQ_1E),
            "16" => Ok(Position::SQ_1F),
            "17" => Ok(Position::SQ_1G),
            "18" => Ok(Position::SQ_1H),
            "19" => Ok(Position::SQ_1I),

            "21" => Ok(Position::SQ_2A),
            "22" => Ok(Position::SQ_2B),
            "23" => Ok(Position::SQ_2C),
            "24" => Ok(Position::SQ_2D),
            "25" => Ok(Position::SQ_2E),
            "26" => Ok(Position::SQ_2F),
            "27" => Ok(Position::SQ_2G),
            "28" => Ok(Position::SQ_2H),
            "29" => Ok(Position::SQ_2I),

            "31" => Ok(Position::SQ_3A),
            "32" => Ok(Position::SQ_3B),
            "33" => Ok(Position::SQ_3C),
            "34" => Ok(Position::SQ_3D),
            "35" => Ok(Position::SQ_3E),
            "36" => Ok(Position::SQ_3F),
            "37" => Ok(Position::SQ_3G),
            "38" => Ok(Position::SQ_3H),
            "39" => Ok(Position::SQ_3I),

            "41" => Ok(Position::SQ_4A),
            "42" => Ok(Position::SQ_4B),
            "43" => Ok(Position::SQ_4C),
            "44" => Ok(Position::SQ_4D),
            "45" => Ok(Position::SQ_4E),
            "46" => Ok(Position::SQ_4F),
            "47" => Ok(Position::SQ_4G),
            "48" => Ok(Position::SQ_4H),
            "49" => Ok(Position::SQ_4I),

            "51" => Ok(Position::SQ_5A),
            "52" => Ok(Position::SQ_5B),
            "53" => Ok(Position::SQ_5C),
            "54" => Ok(Position::SQ_5D),
            "55" => Ok(Position::SQ_5E),
            "56" => Ok(Position::SQ_5F),
            "57" => Ok(Position::SQ_5G),
            "58" => Ok(Position::SQ_5H),
            "59" => Ok(Position::SQ_5I),

            "61" => Ok(Position::SQ_6A),
            "62" => Ok(Position::SQ_6B),
            "63" => Ok(Position::SQ_6C),
            "64" => Ok(Position::SQ_6D),
            "65" => Ok(Position::SQ_6E),
            "66" => Ok(Position::SQ_6F),
            "67" => Ok(Position::SQ_6G),
            "68" => Ok(Position::SQ_6H),
            "69" => Ok(Position::SQ_6I),

            "71" => Ok(Position::SQ_7A),
            "72" => Ok(Position::SQ_7B),
            "73" => Ok(Position::SQ_7C),
            "74" => Ok(Position::SQ_7D),
            "75" => Ok(Position::SQ_7E),
            "76" => Ok(Position::SQ_7F),
            "77" => Ok(Position::SQ_7G),
            "78" => Ok(Position::SQ_7H),
            "79" => Ok(Position::SQ_7I),

            "81" => Ok(Position::SQ_8A),
            "82" => Ok(Position::SQ_8B),
            "83" => Ok(Position::SQ_8C),
            "84" => Ok(Position::SQ_8D),
            "85" => Ok(Position::SQ_8E),
            "86" => Ok(Position::SQ_8F),
            "87" => Ok(Position::SQ_8G),
            "88" => Ok(Position::SQ_8H),
            "89" => Ok(Position::SQ_8I),

            "91" => Ok(Position::SQ_9A),
            "92" => Ok(Position::SQ_9B),
            "93" => Ok(Position::SQ_9C),
            "94" => Ok(Position::SQ_9D),
            "95" => Ok(Position::SQ_9E),
            "96" => Ok(Position::SQ_9F),
            "97" => Ok(Position::SQ_9G),
            "98" => Ok(Position::SQ_9H),
            "99" => Ok(Position::SQ_9I),

            _ => Err(()),
        }
    }
}
